In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
path = "c://ml_dataset/breast_cancer.csv"

In [3]:
data = pd.read_csv(path)
data

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [4]:
data.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [5]:
cc = list(data.columns)
len(cc)

11

In [6]:
X = data.iloc[:,1:-1].values
y = data.iloc[:,-1].values

In [7]:
#Encoding the independent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [8]:
y[:10]

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [9]:
X[:10]

array([[ 5,  1,  1,  1,  2,  1,  3,  1,  1],
       [ 5,  4,  4,  5,  7, 10,  3,  2,  1],
       [ 3,  1,  1,  1,  2,  2,  3,  1,  1],
       [ 6,  8,  8,  1,  3,  4,  3,  7,  1],
       [ 4,  1,  1,  3,  2,  1,  3,  1,  1],
       [ 8, 10, 10,  8,  7, 10,  9,  7,  1],
       [ 1,  1,  1,  1,  2, 10,  3,  1,  1],
       [ 2,  1,  2,  1,  2,  1,  3,  1,  1],
       [ 2,  1,  1,  1,  2,  1,  1,  1,  5],
       [ 4,  2,  1,  1,  2,  1,  2,  1,  1]], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [11]:
X_train[:10]

array([[ 3,  1,  1,  3,  2,  1,  1,  1,  1],
       [ 7,  9,  4, 10, 10,  3,  5,  3,  3],
       [ 5,  2,  4,  1,  1,  1,  1,  1,  1],
       [10,  7,  7,  6,  4, 10,  4,  1,  2],
       [ 2,  1,  1,  1,  2,  1,  3,  1,  1],
       [ 4,  1,  1,  1,  2,  1,  2,  1,  1],
       [ 5,  1,  1,  1,  1,  1,  1,  1,  1],
       [10, 10, 10, 10,  3, 10, 10,  6,  1],
       [ 6,  3,  4,  1,  5,  2,  3,  9,  1],
       [ 3,  1,  1,  1,  2,  1,  1,  1,  1]], dtype=int64)

In [12]:
X_test[:10]

array([[ 8,  3,  4,  9,  3, 10,  3,  3,  1],
       [ 8,  8,  7,  4, 10, 10,  7,  8,  7],
       [ 1,  1,  1,  1,  2,  1,  3,  1,  1],
       [ 1,  1,  2,  2,  2,  1,  3,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  2,  1,  1],
       [ 5,  1,  1,  1,  3,  2,  2,  2,  1],
       [ 1,  1,  3,  1,  1,  1,  2,  1,  1],
       [ 1,  1,  1,  2,  1,  3,  1,  1,  7],
       [ 4,  2,  3,  5,  3,  8,  7,  6,  1],
       [ 4,  1,  2,  1,  2,  1,  2,  1,  1]], dtype=int64)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
#Creating the Artificial Neural network

#Initializing the ANN
ann = tf.keras.models.Sequential()
#Creating the first hidden layer
ann.add(tf.keras.layers.Dense(units = 8, activation = "relu"))
#Creating the second hidden layer
ann.add(tf.keras.layers.Dense(units = 8, activation = "relu"))
#Creating the output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

#Compiling the neaural network
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])
ann.fit(X_train,y_train, batch_size = 32, epochs = 100)

Epoch 1/100
18/18 [==============================] - 2s 5ms/step - loss: 0.5144 - accuracy: 0.8278
Epoch 2/100
18/18 [==============================] - 0s 4ms/step - loss: 0.4111 - accuracy: 0.8828
Epoch 3/100
18/18 [==============================] - 0s 3ms/step - loss: 0.3319 - accuracy: 0.9048
Epoch 4/100
18/18 [==============================] - 0s 3ms/step - loss: 0.2715 - accuracy: 0.9267
Epoch 5/100
18/18 [==============================] - 0s 3ms/step - loss: 0.2256 - accuracy: 0.9322
Epoch 6/100
18/18 [==============================] - 0s 3ms/step - loss: 0.1914 - accuracy: 0.9451
Epoch 7/100
18/18 [==============================] - 0s 3ms/step - loss: 0.1666 - accuracy: 0.9487
Epoch 8/100
18/18 [==============================] - 0s 4ms/step - loss: 0.1474 - accuracy: 0.9579
Epoch 9/100
18/18 [==============================] - 0s 4ms/step - loss: 0.1338 - accuracy: 0.9615
Epoch 10/100
18/18 [==============================] - 0s 4ms/step - loss: 0.1229 - accuracy: 0.9615
Epoch 11/

In [15]:
sc.inverse_transform(X_train[:10])

array([[ 3.,  1.,  1.,  3.,  2.,  1.,  1.,  1.,  1.],
       [ 7.,  9.,  4., 10., 10.,  3.,  5.,  3.,  3.],
       [ 5.,  2.,  4.,  1.,  1.,  1.,  1.,  1.,  1.],
       [10.,  7.,  7.,  6.,  4., 10.,  4.,  1.,  2.],
       [ 2.,  1.,  1.,  1.,  2.,  1.,  3.,  1.,  1.],
       [ 4.,  1.,  1.,  1.,  2.,  1.,  2.,  1.,  1.],
       [ 5.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [10., 10., 10., 10.,  3., 10., 10.,  6.,  1.],
       [ 6.,  3.,  4.,  1.,  5.,  2.,  3.,  9.,  1.],
       [ 3.,  1.,  1.,  1.,  2.,  1.,  1.,  1.,  1.]])

In [16]:
y_train[:10]

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [17]:
#making prediction on a single dataset
prediction = ann.predict(sc.transform([[5,  1,  1,  1,  2,  1,  3,  1,  1]]))
prediction

1/1 [==============================] - 0s 151ms/step


array([[0.0015562]], dtype=float32)

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)[:10])

5/5 [==============================] - 0s 2ms/step
[[1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred > 0.5)
print(cm)
accuracy = accuracy_score(y_test, y_pred > 0.5)
print(f"Accuracy : {accuracy}")

[[78  1]
 [ 2 56]]
Accuracy : 0.9781021897810219
